### ISSUE TITLE
Broken Links in Documentation

### ISSUE THREAD

**Issue by jamiedewitz** [ellucian-developer/experience-maestro-grade-change#1]
In the documentation, under "DataConnect Serverless APIs & Authorization", these 3 links go to 404 pages: 
[DataConnect Serverless APIs](https://resources.elluciancloud.com/bundle/ethos_data_connect_int_design_acn_use/page/t_dc_designer_create_serverless_api.html)
[Ethos Token](https://resources.elluciancloud.com/bundle/ethos_data_connect_int_design_acn_use/page/t_dc_designer_ethos_token_configuration.html)
[User Token](https://resources.elluciancloud.com/bundle/ethos_data_connect_int_design_acn_use/page/t_dc_designer_user_token_configuration.html)

Also, could you please update the links to open in a new tab?

**Comment by Sarav-S** [comment]
@jamiedewitz Thank you for pointing out. Fixed it on 3df454f345f518747e2b68d998b3b369264cc624
